<?php 
namespace App\Services;

use App\Config\GameConfig;
use App\Constants\GameEntitiesConstants;
use App\Resources\GameSessionData;

/**
 * PricingCalculator: A stateless service utility responsible for all financial calculations 
 * related to game sessions, including entry costs and prize pool determination.
 */
class PricingCalculator {

    // Constants 

    /**
     * @var string The configuration key for a game mode's base entry cost.
     */
    private const BASE_COST = 'baseCost';
    /**
     * @var string The configuration key for a game mode's extra card cost.
     */
    private const EXTRA_CARD_COST = 'extraCardCost';

    /**
     * @var GameConfig The configuration DTO containing pricing and timing settings.
     */
    private GameConfig $config;
    
    /**
     * PricingCalculator constructor.
     *
     * @param GameConfig $config The game configuration dependency.
     */
    public function __construct(GameConfig $config) {
        $this->config = $config;
    }
    
    /**
     * Calculates the entry cost for a player based on the game mode and the number of cards chosen.
     *
     * @param string $gameMode The identifier for the current game mode.
     * @param int $numberOfCards The number of cards the player wishes to play with.
     * @return int The total entry cost in game currency.
     */
    public function calculateEntryCost(string $gameMode, int $numberOfCards): int {

        $modeConfig = $this->config->getModeConfig($gameMode);
        
        if (!$modeConfig) {
            return 50; // Default fallback price
        }

        // Calculation: Base Cost + ( (Card Count - 1) * Extra Card Cost )
        return $modeConfig[self::BASE_COST] + (($numberOfCards - 1) * $modeConfig[self::EXTRA_CARD_COST]);
    }
    
    /**
     * Retrieves the ball call interval (in seconds) for the game.
     *
     * @param string $gameMode The game mode identifier (kept for potential future per-mode differences).
     * @return int The time interval (in seconds) between number calls.
     */
    public function getCallInterval(string $gameMode): int {
        // $modeConfig = $this->config->getModeConfig($gameMode);
        // return $modeConfig[self::CALL_INTERVAL] ?? 4;
        return $this->config->callInterval;
    }

    /**
     * Retrieves the configured ball speeds for practice mode.
     *
     * @return array<string, mixed> An array mapping speed levels to their configuration values.
     */
    public function getSpeeds(): array {
        return $this->config->getPracticeBallSpeeds();
    }
    
   /**
     * Calculates the total prize pool for a session by summing the entry costs of all participants.
     *
     * @param GameSessionData $sessionData The object containing all participant data and the session type.
     * @return int The total prize pool generated by all participant entry costs.
     */
    public function calculatePrizePool(GameSessionData $sessionData): int {
        $total = 0;
        
        foreach ($sessionData->participants as $participant) {
            // Recalculate cost for each participant based on their chosen card count
            $total += $this->calculateEntryCost(
                $sessionData->sessionType, 
                $participant[GameEntitiesConstants::NUMBER_OF_CARDS]
            );
        }
        
        return $total;
    }
}