<?php

namespace App\Enums;

/**
 * A centralized definition of all application-specific error codes.
 * The string value of each case maps directly to a code in errors.json.
 */
enum ErrorCode: string
{
    // === Infrastructure & Routing Errors (00) ===
    case INFRA_UNEXPECTED_ERROR = 'ERR_00_INFRA_UNEXPECTED';
    case INFRA_DATABASE_ERROR = 'ERR_00_INFRA_DATABASE';
    case ROUTING_NOT_FOUND = 'ERR_00_ROUTING_NOT_FOUND';
    case INFRA_CACHE_CONNECTION_FAILED = 'ERR_00_INFRA_CACHE_CONNECTION';


    // === Authentication & Authorization Errors (01) ===
    case AUTH_ACCESS_TOKEN_MISSING = 'ERR_01_AUTH_ACCESS_TOKEN_MISSING';
    case AUTH_ACCESS_TOKEN_EXPIRED = 'ERR_01_AUTH_ACCESS_TOKEN_EXPIRED'; 
    case AUTH_ACCESS_TOKEN_INVALID = 'ERR_01_AUTH_ACCESS_TOKEN_INVALID';
    case AUTH_REFRESH_TOKEN_MISSING = 'ERR_01_AUTH_REFRESH_TOKEN_MISSING';
    case AUTH_REFRESH_TOKEN_INVALID_OR_REVOKED = 'ERR_01_AUTH_REFRESH_TOKEN_INVALID';
    case AUTH_FORBIDDEN = 'ERR_01_AUTH_FORBIDDEN';
    case AUTH_USERNAME_TAKEN = 'ERR_01_AUTH_USERNAME_TAKEN';
    case AUTH_UNAUTHORIZED = 'ERR_01_AUTH_UNAUTHORIZED';
    case AUTH_MISSING_SIGNATURE = 'ERR_01_AUTH_MISSING_SIGNATURE';
    case AUTH_INVALID_SIGNATURE = 'ERR_01_AUTH_INVALID_SIGNATURE';
    case AUTH_INVALID_CREDENTIALS = 'ERR_01_AUTH_INVALID_CREDENTIALS';

    // === Validation Errors (02) ===
    case VALIDATION_MISSING_FIELDS = 'ERR_02_VALIDATION_MISSING_FIELDS';
    case VALIDATION_USERNAME_INVALID_FORMAT = 'ERR_02_VALIDATION_USERNAME_FORMAT';
    case VALIDATION_AVATAR_INVALID = 'ERR_02_VALIDATION_AVATAR_INVALID';
    case VALIDATION_USER_ID_MISSING = 'ERR_02_VALIDATION_USER_ID_MISSING';
    case VALIDATION_GAME_INVALID_REQUEST = 'ERR_02_GAME_INVALID_REQUEST';
    case VALIDATION_GAME_MODE_UNSUPPORTED = 'ERR_02_GAME_MODE_UNSUPPORTED';

    // === Resource Errors (03) ===
    case RESOURCE_USER_NOT_FOUND = 'ERR_03_RESOURCE_USER_NOT_FOUND';
    
    // === Game Logic Errors (04) ===
    case GAME_INVALID_BINGO_CALL = 'ERR_04_GAME_INVALID_BINGO_CALL';
    case GAME_NO_BINGO = 'ERR_04_GAME_NO_BINGO';
    case GAME_SESSION_NOT_FOUND = 'ERR_04_GAME_SESSION_NOT_FOUND';
    case GAME_INSUFFICIENT_FUNDS = 'ERR_04_GAME_INSUFFICIENT_FUNDS';

    case GAME_INVALID_REQUEST = 'ERR_04_GAME_INVALID_REQUEST';

    case GAME_MODE_UNSUPPORTED = 'ERR_04_GAME_MODE_UNSUPPORTED';
}